### ISSUE TITLE
P&R Parking Kalkofenstraße not tagged as P&R

### ISSUE THREAD

**Issue by hbruch** [transportkollektiv/digitransit-ui#4]
The parking Kalkofenstraße is mapped as multiple building layers but not amenity=parking;park_ride=yes. 

As a result, instead of this park&ride, a smaller one in the south is recommended for P&R connections.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/2187389/67530479-76925a00-f6bf-11e9-8356-3384634df4e7.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2187389/67530589-da1c8780-f6bf-11e9-839c-eb7e1a738b48.png">

**Comment by leonardehrenfried** [comment]
I added park_ride=train.

https://www.openstreetmap.org/changeset/76225412

**Comment by hbruch** [comment]
Additionally, amenity=parking is required for OTP to consider park_ride=train. With this [changeset](https://www.openstreetmap.org/changeset/77638555) I added park_ride=yes to the ground floor (park_ride=yes instead of park_ride=train, as there is a bus_station as well).
